ADD token when readJson from remote
EndBug/version-check pull request #27
Opened 2020-10-07 13:41 UTC by AlexRex

As stated in the issue: https://github.com/EndBug/version-check/issues/8#issuecomment-704931812.

It will be nice to be able to use the `::before` tag when using private repos. Therefore, this PR.

2020-10-07 15:22 UTC, EndBug requested changes
Hi, thank you for the PR!
It's not working for me though, are you sure that's the correct authentication header? Check out the comment I left and let me know if that works ;)

2020-10-07 15:22 UTC, EndBug commented on src/main.ts
> +      Authorization: `Bearer ${token}`
```suggestion
      Authorization: `token ${token}`
```
Shouldn't this be `token` instead of `Bearer`? 
I've seen that [here](https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#authentication) and in some Stack Overflow answers they use it like this...

2020-10-08 07:17 UTC, AlexRex commented
> Hi, thank you for the PR!
> It's not working for me though, are you sure that's the correct authentication header? Check out the comment I left and let me know if that works ;)

That's strange! It is actually working for me with `Bearer`, but you're right, the docs says `token` instead. I guess both work, but better to keep the one documented officially.

2020-10-08 10:34 UTC, EndBug approved these changes
Ok, I found out what the problem was: I was testing the action using the branch on your fork, but that didn't have an updated build, and so wasn't running your changes 😅 
After committing the build it worked just right. Maybe it would have worked the original way too, with `Bearer`, but at this point we'll keep `token`
I'll add it in the next minor version ;)

2020-10-08 10:35 UTC, EndBug commented
@all-contributors add @AlexRex for code

2020-10-08 10:36 UTC, AlexRex commented
@EndBug Argh! I thought about it actually, but as the contribution guidelines stated to don't push the built code 😅 .

Thanks for the changes :)

2020-10-08 10:39 UTC, EndBug commented
My bad then 😅 
I'll add a git hook to enforce the build on every commit

2020-10-08 10:39 UTC, merged

2020-10-08 11:22 UTC, EndBug commented
Published in `v1.6.0` (`v1`, `latest`) 🎉 
Thanks again for the PR :)