diff-search option not working because getInput returns a string -> if (getInput('diff-search')) is always true.
EndBug/version-check pull request #281
Opened 2024-04-11 00:52 UTC by mrkpatchaa

2024-04-13 03:22 UTC, EndBug requested changes
Nice catch, thanks!
But we should use `getBooleanInput` instead ;)

2024-04-13 08:39 UTC, mrkpatchaa commented
@EndBug just changed 😄 I didn't know this function exists. I was just playing around and finding a way to fix it. 
Thanks.

2024-04-15 18:10 UTC, EndBug approved these changes

2024-04-15 18:10 UTC, merged

2024-04-15 18:11 UTC, EndBug commented
Thanks again for the fix! Will publish right away.

@all-contributors please add @mrkpatchaa for their bug contribution